version: '3.1'

services:
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'root'
      MYSQL_DATABASE: 'mentor'
    volumes:
      - mariadb_data:/database/var/lib/mysql
    ports:
      - 3307:3306

volumes:
  mariadb_data:
