export enum EnvVariable {
  NODE_ENV = 'NODE_ENV',

  PORT = 'PORT',

  DATABASE_HOST = 'DATABASE_HOST',
  DATABASE_PORT = 'DATABASE_PORT',
  DATABASE_USERNAME = 'DATABASE_USERNAME',
  DATABASE_PASSWORD = 'DATABASE_PASSWORD',
  DATABASE_NAME = 'DATABASE_NAME',
  DATABASE_CONFIG_FILE_PATH = 'DATABASE_CONFIG_FILE_PATH',
  DATABASE_MIGRATION_FOLDER_PATH = 'DATABASE_MIGRATION_FOLDER_PATH',

  JWT_SECRET = 'JWT_SECRET',
}
